/**
 * Export.
 *
 * Produces a Terraform module laid out the way a repository expects it, plus
 * an Azure Pipelines definition that runs it. The pipeline is the deliverable
 * the design is actually for: nothing here runs Terraform in the browser or
 * asks for a credential.
 */

import JSZip from 'jszip';
import { generate, type BackendConfig, type GeneratedFile } from './generate';
import type { Design, ProviderPack } from './types';

export interface PipelineOptions {
  /** Azure DevOps service connection (an ARM service principal). */
  serviceConnection: string;
  /** Folder the module lands in, relative to the repository root. */
  workingDirectory: string;
  /** Azure DevOps environment gating the apply stage, where approvals live. */
  environment: string;
  terraformVersion: string;
  /** Branch that is allowed to apply. */
  defaultBranch: string;
}

export interface ExportOptions {
  backend: BackendConfig;
  pipeline: PipelineOptions;
  includePipeline: boolean;
  includeReadme: boolean;
}

export const defaultPipelineOptions = (): PipelineOptions => ({
  serviceConnection: 'azure-terraform',
  workingDirectory: 'infra',
  environment: 'production',
  terraformVersion: '1.9.5',
  defaultBranch: 'main',
});

export const defaultBackend = (): BackendConfig => ({
  type: 'azurerm',
  config: {
    resource_group_name: 'rg-terraform-state',
    storage_account_name: 'sttfstate',
    container_name: 'tfstate',
    key: 'infrastructure.tfstate',
  },
});

/* -------------------------------------------------------------------------- */
/* Azure Pipelines                                                            */
/* -------------------------------------------------------------------------- */

/**
 * A three-stage pipeline: validate, plan, apply.
 *
 * The plan is published as an artifact and the apply consumes that exact
 * plan, so what a reviewer approves is what gets applied. Approvals are
 * attached to the Azure DevOps environment rather than encoded here.
 */
export function azurePipeline(options: PipelineOptions, backend: BackendConfig): string {
  const config = backend.config ?? {};

  // Held unindented; each call site indents them to its own depth.
  const backendInputs =
    backend.type === 'azurerm'
      ? [
          `backendServiceArm: '${options.serviceConnection}'`,
          `backendAzureRmResourceGroupName: '${config.resource_group_name ?? ''}'`,
          `backendAzureRmStorageAccountName: '${config.storage_account_name ?? ''}'`,
          `backendAzureRmContainerName: '${config.container_name ?? ''}'`,
          `backendAzureRmKey: '${config.key ?? ''}'`,
        ]
      : [];

  const init = (indent: string) =>
    [
      `${indent}- task: TerraformTaskV4@4`,
      `${indent}  displayName: Terraform init`,
      `${indent}  inputs:`,
      `${indent}    provider: azurerm`,
      `${indent}    command: init`,
      `${indent}    workingDirectory: $(workingDirectory)`,
      // Backend settings are further inputs, so they sit at the same depth.
      ...backendInputs.map((line) => `${indent}    ${line}`),
    ].join('\n');

  const installer = (indent: string) =>
    [
      `${indent}- task: TerraformInstaller@1`,
      `${indent}  displayName: Install Terraform $(terraformVersion)`,
      `${indent}  inputs:`,
      `${indent}    terraformVersion: $(terraformVersion)`,
    ].join('\n');

  return `# Generated by Terraform Builder.
#
# Prerequisites in Azure DevOps:
#   1. An ARM service connection named '${options.serviceConnection}' with rights
#      on the target subscription and on the state storage account.
#   2. An environment named '${options.environment}' carrying the approval checks
#      that gate the apply stage.
#   3. The Terraform extension by Microsoft DevLabs installed in the organisation.

trigger:
  branches:
    include:
      - ${options.defaultBranch}
  paths:
    include:
      - ${options.workingDirectory}/**

pr:
  branches:
    include:
      - ${options.defaultBranch}
  paths:
    include:
      - ${options.workingDirectory}/**

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '${options.terraformVersion}'
  workingDirectory: '$(System.DefaultWorkingDirectory)/${options.workingDirectory}'

stages:
  - stage: validate
    displayName: Validate
    jobs:
      - job: validate
        displayName: Format and validate
        steps:
${installer('          ')}

          - script: terraform fmt -check -recursive
            displayName: Check formatting
            workingDirectory: $(workingDirectory)

${init('          ')}

          - task: TerraformTaskV4@4
            displayName: Terraform validate
            inputs:
              provider: azurerm
              command: validate
              workingDirectory: $(workingDirectory)

  - stage: plan
    displayName: Plan
    dependsOn: validate
    condition: succeeded()
    jobs:
      - job: plan
        displayName: Terraform plan
        steps:
${installer('          ')}

${init('          ')}

          - task: TerraformTaskV4@4
            displayName: Terraform plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: $(workingDirectory)
              environmentServiceNameAzureRM: '${options.serviceConnection}'
              commandOptions: '-input=false -out=$(Build.ArtifactStagingDirectory)/tfplan'

          # The apply stage consumes this exact plan, so what is reviewed is
          # what is applied.
          - publish: $(Build.ArtifactStagingDirectory)/tfplan
            artifact: tfplan
            displayName: Publish plan

  - stage: apply
    displayName: Apply
    dependsOn: plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${options.defaultBranch}'))
    jobs:
      - deployment: apply
        displayName: Terraform apply
        environment: '${options.environment}'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

${installer('                ')}

                - download: current
                  artifact: tfplan
                  displayName: Download plan

${init('                ')}

                - task: TerraformTaskV4@4
                  displayName: Terraform apply
                  inputs:
                    provider: azurerm
                    command: apply
                    workingDirectory: $(workingDirectory)
                    environmentServiceNameAzureRM: '${options.serviceConnection}'
                    commandOptions: '-input=false $(Pipeline.Workspace)/tfplan/tfplan'
`;
}

/* -------------------------------------------------------------------------- */
/* Bundle                                                                     */
/* -------------------------------------------------------------------------- */

function readme(design: Design, options: ExportOptions): string {
  const config = options.backend.config ?? {};
  return `# ${design.name}

Generated by Terraform Builder. Edit freely — this is ordinary Terraform.

## Layout

| File | Purpose |
| --- | --- |
| \`providers.tf\` | Provider requirements and remote state backend |
| \`main.tf\` | The resources themselves |
| \`variables.tf\` | Inputs, including anything marked sensitive |
| \`outputs.tf\` | Resource ids for downstream stacks |

## Running it locally

\`\`\`bash
terraform init
terraform plan
\`\`\`

Sensitive values are declared as variables and are deliberately absent from the
code. Supply them at plan time, from a \`*.auto.tfvars\` file that is not
committed, or from pipeline variables marked secret.

## Running it in Azure DevOps

\`azure-pipelines.yml\` defines validate → plan → apply.

1. Commit this folder to \`${options.pipeline.workingDirectory}/\` in your repository.
2. Create an ARM service connection named \`${options.pipeline.serviceConnection}\`.
3. Create an environment named \`${options.pipeline.environment}\` and attach approvals to it.
4. Install the Terraform extension by Microsoft DevLabs in your organisation.
5. Create a pipeline pointing at \`azure-pipelines.yml\`.

State is kept in the \`${config.container_name ?? 'tfstate'}\` container of storage
account \`${config.storage_account_name ?? ''}\` under the key
\`${config.key ?? ''}\`. Create that storage account before the first run — the
backend cannot bootstrap itself.
`;
}

const GITIGNORE = `.terraform/
*.tfstate
*.tfstate.*
*.tfvars
!*.auto.tfvars.example
crash.log
override.tf
override.tf.json
`;

/** Assembles every file the export contains. */
export function buildBundle(
  design: Design,
  pack: ProviderPack,
  options: ExportOptions,
): GeneratedFile[] {
  const { files } = generate(design, pack, { backend: options.backend });
  const bundle = [...files];

  if (options.includePipeline) {
    bundle.push({
      path: 'azure-pipelines.yml',
      contents: azurePipeline(options.pipeline, options.backend),
    });
  }
  if (options.includeReadme) {
    bundle.push({ path: 'README.md', contents: readme(design, options) });
  }
  bundle.push({ path: '.gitignore', contents: GITIGNORE });

  // The design itself travels with the code, so the diagram can be reopened
  // and edited later rather than reverse-engineered.
  bundle.push({
    path: '.terraform-builder.json',
    contents: `${JSON.stringify(design, null, 2)}\n`,
  });

  return bundle;
}

/** Slug suitable for a file name. */
export const slugify = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'infrastructure';

export async function downloadZip(files: GeneratedFile[], name: string): Promise<void> {
  const zip = new JSZip();
  for (const file of files) zip.file(file.path, file.contents);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${slugify(name)}.zip`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/** Downloads a single file, for the "just give me main.tf" case. */
export function downloadFile(file: GeneratedFile): void {
  const blob = new Blob([file.contents], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = file.path;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
